### ISSUE TITLE
opa binary not found

### ISSUE THREAD

**Issue by jwineinger** [vgramer/opa-idea-plugin#60]
# Actual Behavior
Running an eval configuration returns this error:
Cannot run program "opa": error=2, No such file or directory

# Expected  Behavior
Running the eval configuration works

# How To Reproduce

# Environment
 - OS: macOS 10.14.6

 - OPA version: 0.24.0

 - IDE full name and version: GoLand 2020.2.3

 - plugin version: 0.1.0.0-202

# Additional context
I have my opa binary in /usr/local/bin which is on my path and running `opa` from terminal (within and without GoLand/Intellij) works just fine. I've even copied the binary (with 755 perms) into the project workspace without success.

Can you give more information in the docs on what to do to make sure "OPA binary must be in the path"? Or perhaps have a configuration setting for the path to the opa binary?

**Comment by vgramer** [comment]
Hi @jwineinger, 

The opa binary must be named `opa`. By in the path, I mean opa binary must be in one of the folders defined by the environment variable  `PATH`.

Obviously `/usr/local/bin`  is in the path.

You can have this error if the opa binary is not executable. Can you run the command `which opa` and ensure the binary is return by this command is executable?

**Comment by jwineinger** [comment]
It seems to be setup correctly to me.

```
$ ls -l `which opa`
-rwxr-xr-x  1 jawineinger  259459109  22060432 Oct 15 10:54 /usr/local/bin/opa

$ opa
An open source project to policy-enable your service.

Usage:
  opa [command]

Available Commands:
  bench       Benchmark a Rego query
....
```

**Comment by vgramer** [comment]
@jwineinger 

Permission looks good to me.  Can you check goland is run with the same user ? 

For information I am on mac os 10.15.7 with the same version of opa and GoLand and I can not reproduce the bug.
```bash
 $ ls -alp@ /usr/local/bin/opa
-rwxr-xr-x@ 1 vince  staff  22060432 19 oct 15:13 /usr/local/bin/opa
	com.apple.macl	      72
	com.apple.metadata:kMDItemWhereFroms	     645
$ opa version
Version: 0.24.0
Build Commit: b69b80b
Build Timestamp: 2020-10-13T21:36:15Z
Build Hostname: ffabd2c9ce42
Go Version: go1.14.9
```

**Comment by jwineinger** [comment]
`ps aux` tells me the goland process is running with the user and `whoami` from a terminal inside of goland shows the same user. I'm not sure how else to check how goland invokes the opa binary.

**Comment by vgramer** [comment]
@jwineinger  sorry for the late response. 

Can you please enable debug for the class in charge of executing a process, run your configuration, and post the logs. 

Here is the procedure:
1. go menu `Help->Diagnotic Tools->Debug Log Settings...` then add `#com.intellij.execution.configurations.GeneralCommandLine`. 

1. To find the logs go to menu `Help->Show Log in Finder`, the log file is named `idea.log`


For example I made a test by removing execution right on my opa binary and got logs look liking this:

```
2020-10-21 14:10:39,361 [ 143053]  DEBUG - figurations.GeneralCommandLine - Executing [opa eval -f pretty -b /Users/vince/rego-test-final/src --input /Users/vince/rego-test-final/src/input.json data.main.rule2] 
2020-10-21 14:10:39,362 [ 143054]  DEBUG - figurations.GeneralCommandLine -   environment: {} (+CONSOLE) 
2020-10-21 14:10:39,362 [ 143054]  DEBUG - figurations.GeneralCommandLine -   charset: UTF-8 
2020-10-21 14:10:39,362 [ 143054]  DEBUG - figurations.GeneralCommandLine - Building process with commands: [opa, eval, -f, pretty, -b, /Users/vince/rego-test-final/src, --input, /Users/vince/rego-test-final/src/input.json, data.main.rule2] 
2020-10-21 14:10:39,366 [ 143058]  DEBUG - figurations.GeneralCommandLine -  
java.io.IOException: Cannot run program "opa": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:422)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:99)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:47)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:24)
	at com.intellij.execution.process.ProcessHandlerFactoryImpl.createColoredProcessHandler(ProcessHandlerFactoryImpl.java:33)
	at org.openpolicyagent.ideaplugin.ide.runconfig.OpaEvalRunProfileState.startProcess(OpaEvalRunProfileState.kt:42)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:147)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:208)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 42 more
2020-10-21 14:10:39,369 [ 143061]   INFO - xecution.runners.ExecutionUtil - Error running 'eval data.main.rule2':<br>Cannot run program "opa": error=2, No such file or directory 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "opa": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:426)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:99)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:47)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:24)
	at com.intellij.execution.process.ProcessHandlerFactoryImpl.createColoredProcessHandler(ProcessHandlerFactoryImpl.java:33)
	at org.openpolicyagent.ideaplugin.ide.runconfig.OpaEvalRunProfileState.startProcess(OpaEvalRunProfileState.kt:42)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:147)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:208)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: Cannot run program "opa": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:422)
	... 39 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 42 more
```

**Comment by jwineinger** [comment]
Ah, that was helpful. I think this is probably the culprit, though I'm not quite sure how to fix it. MacOS's protections prevent changes to any of those dirs, and I'd rather not disable those protections. Do you know how to change the PATH that GoLand uses?
```
2020-10-21 08:45:34,516 [  19324]  DEBUG - figurations.GeneralCommandLine -   environment: {... PATH=/usr/bin:/bin:/usr/sbin:/sbin, ...
```

**Comment by vgramer** [comment]
You can edit you `~/.zshrc` to add another folder to `PATH` environment variable and reload your session.  Or you can create a launcher script to run Goland from the terminal and export a modified `PATH`  environment variable before running the launcher.

To create a launcher, go in menu `Tools -> Create Command-line launcher...` (it will redirect you to the doc )

**Comment by jwineinger** [comment]
I was able to change the path by editing the GoLand.app/Contents/Info.plist file and add the following
```    
    <key>LSEnvironment</key>
    <dict>
        <key>PATH</key>
        <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin</string>
    </dict>
```

Creating a Command-Line launcher worked as well but I didn't want to have to use that every time.
